-- Executed once by the shared delivery pipeline before the deployment rolls.
-- The application runtime identity is intentionally not granted DDL rights.
CREATE TABLE IF NOT EXISTS vets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name TEXT
);

CREATE INDEX IF NOT EXISTS idx_vets_last_name ON vets (last_name);
